app:
  port: 3001
  resource:
    imageResourcePath: "/app/resource"
    address: resource.example.com
  serviceName: service
  serviceUrl: http://localhost:3000
  jwtSecret: secret

db:
  allowSync: false
  # sequelize-typscript
  config: 
    dialect: postgres
    dialectOptions:
      autoJsonMap: false
    database: jewerly
    username: root
    password: password
    host: localhost
    port: 5432
    sync:
      force: false
      alter:
        drop: false
    replication:
      read:
        - database: jewerly
          username: root
          password: password
          host: localhost
          port: 5432
      write: 
        database: jewerly
        username: root
        password: password
        host: localhost
        port: 5432
    timezone: +09:00

# aws-sdk ConfigurationOptions
aws:
  signatureVersion: v4
  region: "ap-northeast-2"
  # IF USE AWS. not required
  s3Endpoint: "http://127.0.0.1:9000"
  credentials:
    - accessKeyId: somekey
      secretAccessKey: somesecret

keycloak:
  authServerUrl: http://localhost:8180/auth
  realm: nest-example
  clientId: nest-api
  secret: 05c1ff5e-f9ba-4622-98e3-c4c9d280546e
  cookieKey: KEYCLOAK_JWT
  logLevels:
    - info

swagger:
  enable: true
  urls:
    - url: https://api.staging.example.com
      name: staging
    - url: http://localhost:3001
      name: local
    - url: https://api.example.com
      name: product

NODE_ENV: development
