app:
  port: 3001
  resource:
    imageResourcePath: "/app/resource"
    address: resource.example.com
  serviceName: service
  serviceUrl: http://localhost:3000

db:
  allowSync: false
  initKorDic: false
  # sequelize-typscript
  config: 
    dialect: postgres
    dialectOptions:
      autoJsonMap: false
    database: raviluz
    username: postgres
    password: postgres
    host: postgres
    port: 5432
    sync:
      force: false
      alter:
        drop: false
    replication:
      read:
        - database: raviluz
          username: postgres
          password: postgres
          host: postgres
          port: 5432
      write: 
        database: raviluz
        username: postgres
        password: postgres
        host: postgres
        port: 5432
    timezone: +09:00

# aws-sdk ConfigurationOptions
aws:
  signatureVersion: v4
  region: ap-northeast-2
  bucketName: dev
  s3Endpoint: http://minio:9000
  accessKeyId: minioadmin
  secretAccessKey: minioadmin

keycloak:
  authServerUrl: http://keycloak:8080/auth
  realm: operator-dev
  clientId: sms-api
  secret: 07y38dgtt73A6tm0lJZRnXevPUI0XuBa

NODE_ENV: development
