app:
  port: 3001
  resourceAddress: resource.example.com


db:
  allowSync: false
  initKorDic: false
  # sequelize-typscript
  config: 
    dialect: postgres
    dialectOptions:
      autoJsonMap: false
    database: raviluz
    username: postgres
    password: postgres
    host: postgres
    port: 5432
    sync:
      force: false
      alter:
        drop: false
    replication:
      read:
        - database: raviluz
          username: postgres
          password: postgres
          host: postgres
          port: 5432
      write: 
        database: raviluz
        username: postgres
        password: postgres
        host: postgres
        port: 5432
    timezone: +09:00

# aws-sdk ConfigurationOptions
aws:
  signatureVersion: v4
  region: ap-northeast-2
  bucketName: dev
  s3Endpoint: http://minio:9000
  accessKeyId: minioadmin
  secretAccessKey: minioadmin

keycloak:
  authServerUrl: http://keycloak:8080/auth
  realm: raviluz
  clientId: admin-api
  secret: 318ce042-8f42-42f1-965c-88f3c48c0e7d

NODE_ENV: development
