app:
  port: 3001
  resource:
    region: "ap-northeast-2"
    bucket: "bucket"
    address: resource.example.com
  serviceName: service
  serviceUrl: http://localhost:3000
  systemEMailAddress: noreply@example.com
  jwtSecret: secret
  slackBot: 
    enable: false
    token: "something token"
    channel: targetChannel without "#"
db:
  allowSync: false
user:
  operator:
    - username: shopoperator
      password: sh0pOperatorTmpPwd
      email: dummy@dummy.com
      name: 운영자
      phone: "01000000000"

client:
  - name: "shop manager client"
    clientId: "shopClient"
    clientSecret: "shopClient1234"
    scope: operator
    grants: ["password", "refresh_token"]
    redirectUris: ["http://localhost:3000/redirect"]
    accessTokenLifetime: 3600
    refreshTokenLifetime: 7200


swagger:
  enable: true
  urls:
    - url: https://api.staging.example.com
      name: staging
    - url: http://localhost:3001
      name: local
    - url: https://api.example.com
      name: product

NODE_ENV: development

# BUILD TEST
test:
  client:
    admin:
      clientId: shopClient
      clientSecret: shopClient1234
      redirectUri: http://localhost:3000/redirect
  user:
    admin:
      username: shopoperator
      password: sh0pOperatorTmpPwd
      scope: operator
