app:
  port: 3001
  resource:
    region: "ap-northeast-2"
    bucket: "bucket"
  serviceName: service
  serviceUrl: http://localhost:3000
  systemEMailAddress: noreply@example.com
db:
  allowSync: false

NODE_ENV: development
